# Generated by Django 4.2.23 on 2026-04-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTotal',
            fields=[
                ('item_total_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(default='', max_length=100)),
                ('total_quantity', models.IntegerField(default=0)),
                ('available_quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'item_totals',
                'managed': True,
            },
        ),
    ]
