# Generated by Django 4.2.23 on 2026-04-15 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_itemtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.itemtotal'),
        ),
    ]
