# Generated by Django 4.2.23 on 2026-04-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_transaction_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_type',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
