# Generated by Django 4.2.23 on 2026-04-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transaction_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_type',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
