# Generated by Django 4.2.23 on 2026-04-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_transaction_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='itemtotal',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='itemtotal',
            name='total_quantity',
        ),
    ]
