# Generated by Django 6.0.5 on 2026-05-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='to_user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_user_id',
            field=models.CharField(db_column='to_user_id', default='1', max_length=255),
            preserve_default=False,
        ),
    ]
