# Generated by Django 6.0.5 on 2026-05-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_transaction_to_user_transaction_to_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='allocated_items',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='api.item'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='allocated_items',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='api.item'),
        ),
    ]
