# Generated by Django 4.2.23 on 2026-04-15 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transaction_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(db_column='item_total_id', on_delete=django.db.models.deletion.CASCADE, to='api.itemtotal'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction',
            field=models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, to='api.transaction'),
        ),
    ]
