# Generated by Django 4.2.23 on 2026-04-20 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_item_total_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(db_column='item_total_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.itemtotal')),
            ],
            options={
                'db_table': 'bookings',
                'managed': True,
            },
        ),
    ]
